FROM php:8.3-apache

# Install PDO extensions
RUN docker-php-ext-install pdo_mysql

RUN a2enmod rewrite

COPY . /var/www/html/
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf

WORKDIR /var/www/html
